### ISSUE TITLE
Newsletter signup error styling

### ISSUE THREAD

**Issue by jsconfhi** [jsconfhi/splash#1]

**Comment by jkup** [comment]
![screen shot 2018-05-19 at 8 40 25 pm](https://user-images.githubusercontent.com/490294/40275489-e45c94f4-5ba4-11e8-978b-b6da507713a2.png)

**Comment by comp615** [comment]
I think I fixed this now with 289739cafcc29064a8904e17b95f4ea16f23eff2...Still not the most beautiful, but maybe good enough
